### ISSUE TITLE
Evaluating Dicom files with invalid content 

### ISSUE THREAD

**Issue by tznind** [SMI/IsIdentifiable#130]
OverflowException in IsIdentifiable when parsing decimal
Bug Report
What happened?
IsIdentifiable service crashed while processing a message.

The (anonymised) file it is trying to process contains a DecimalString tag which does not have a valid value when parsed to a decimal type by DicomTypeTranslaterReader. The particular tag in question isn't logged, but from inspection is likely one of the tags in scientific notation which is larger than the bounds of a C# decimal.

**Expected result**
IsIdentifiable should ignore invalid data when performing its analysis 

```
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Decimal.Parse(String s, NumberStyles style, IFormatProvider provider)
   at FellowOakDicom.DicomDecimalString.<>c__6`1.<Get>b__6_0(String x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FellowOakDicom.DicomDecimalString.Get[T](Int32 item)
   at FellowOakDicom.DicomDataset.GetValues[T](DicomTag tag)
   at DicomTypeTranslation.DicomTypeTranslaterReader.GetValueFromDatasetWithMultiplicity[TNaturalType](DicomDataset dataset, DicomTag tag)
   at DicomTypeTranslation.DicomTypeTranslaterReader.GetCSharpValue(DicomDataset dataset, DicomItem item)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomItem(IFileInfo fi, DicomFile dicomFile, DicomDataset dataset, DicomItem dicomItem)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomItem(IFileInfo fi, DicomFile dicomFile, DicomDataset dataset, DicomItem dicomItem)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomItem(IFileInfo fi, DicomFile dicomFile, DicomDataset dataset, DicomItem dicomItem)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomItem(IFileInfo fi, DicomFile dicomFile, DicomDataset dataset, DicomItem dicomItem)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomItem(IFileInfo fi, DicomFile dicomFile, DicomDataset dataset, DicomItem dicomItem)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomItem(IFileInfo fi, DicomFile dicomFile, DicomDataset dataset, DicomItem dicomItem)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomItem(IFileInfo fi, DicomFile dicomFile, DicomDataset dataset, DicomItem dicomItem)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomItem(IFileInfo fi, DicomFile dicomFile, DicomDataset dataset, DicomItem dicomItem)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomFile(IFileInfo fi)
   at Microservices.IsIdentifiable.Service.TesseractStanfordDicomFileClassifier.Classify(IFileInfo dcm) in /home/runner/work/SmiServices/SmiServices/src/microservices/Microservices.IsIdentifiable/Service/TesseractStanfordDicomFileClassifier.cs:line 38

```

@rkm I have replicated this internal issue reported in SmiServices here because I think that it applies here too.  Regardless of what solution we apply to the services we shouldn't have IsIdentifiable failing because of invalid data in the first place (hence this ticket).

**Comment by tznind** [comment]
I ran on the grassroots conformance test images (https://sourceforge.net/projects/gdcm/files/gdcmConformanceTests/gdcmConformanceTests/)

```
thomas@thomas-CF-31WBLAHLM:~$ ./IsIdentifiable/ii/bin/Debug/net6.0/ii dir -d ./testdicoms2/gdcmConformanceTests --tessdirectory ./IsIdentifiable/data/tessdata/ --storereport
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
2022-08-02 13:07:25.5458| INFO|IsIdentifiable.Runners.DicomFileRunner|Recursing from Directory: ./testdicoms2/gdcmConformanceTests||
2022-08-02 13:07:26.2082| INFO|IsIdentifiable.Runners.DicomFileRunner|Processing '/home/thomas/testdicoms2/gdcmConformanceTests/SignedShortLosslessBug.dcm'||
2022-08-02 13:07:26.2338| INFO|IsIdentifiable.Runners.DicomFileRunner| Frame 0 in '/home/thomas/testdicoms2/gdcmConformanceTests/SignedShortLosslessBug.dcm'||
2022-08-02 13:07:27.3514| INFO|IsIdentifiable.Runners.DicomFileRunner|Processing '/home/thomas/testdicoms2/gdcmConformanceTests/CR-MONO1-10-chest_LossyJ2K.dcm'||
2022-08-02 13:07:27.3514| INFO|IsIdentifiable.Runners.DicomFileRunner| Frame 0 in '/home/thomas/testdicoms2/gdcmConformanceTests/CR-MONO1-10-chest_LossyJ2K.dcm'||
Unhandled exception. System.ApplicationException: Could not run Tesseract on '/home/thomas/testdicoms2/gdcmConformanceTests/CR-MONO1-10-chest_LossyJ2K.dcm'
 ---> FellowOakDicom.Imaging.Codec.DicomCodecException: Decoding dataset with transfer syntax: JPEG 2000 Image Compression (Lossless Only) is not supported.
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.DecodeFrame(DicomDataset dataset, Int32 frame)
   at FellowOakDicom.Imaging.DicomImage.GetFrameIndex(Int32 frame)
   at FellowOakDicom.Imaging.DicomImage.RenderImage(Int32 frame)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds) in /home/thomas/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 242
   --- End of inner exception stack trace ---
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds) in /home/thomas/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 342
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomFile(IFileInfo fi) in /home/thomas/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 154
   at IsIdentifiable.Runners.DicomFileRunner.ProcessDirectory(String root) in /home/thomas/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 126
   at IsIdentifiable.Runners.DicomFileRunner.Run() in /home/thomas/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 115
   at IsIdentifiable.Program.Run(IsIdentifiableDicomFileOptions opts) in /home/thomas/IsIdentifiable/ii/Program.cs:line 80
   at IsIdentifiable.Program.<>c.<Main>b__2_2(IsIdentifiableDicomFileOptions o) in /home/thomas/IsIdentifiable/ii/Program.cs:line 55
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at IsIdentifiable.Program.Main(String[] args) in /home/thomas/IsIdentifiable/ii/Program.cs:line 48
Aborted
```

Hard crash is less than ideal, I think desired default behavior is to skip over bad images and return a count of failed images.  This will give a nonzero exit code which is good and we can log too.
