### ISSUE TITLE
view is not part of the hierarchy with example report

### ISSUE THREAD

**Issue by rkm** [SMI/IsIdentifiable#289]
When launching `ii` from the latest commit on main with the included example CSV:

```console
$ ./ii review -f ../IsIdentifiable-main/ii/ExampleReport.csv
...
2023-03-30 16:21:00.3120|ERROR|IsIdentifiable.Redacting.ReviewerRunner|Application crashed|System.ArgumentException: the specified view is not part of the hierarchy of this view
   at Terminal.Gui.View.SetFocus(View view)
   at Terminal.Gui.View.FocusFirst()
   at Terminal.Gui.Toplevel.WillPresent()
   at Terminal.Gui.Application.Begin(Toplevel toplevel)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
   at IsIdentifiable.Redacting.ReviewerRunner.Run() in /nimble/work/software/IsIdentifiable-main/ii/ReviewerRunner.cs:line 138|
```

**Comment by rkm** [comment]
This does not occur in the v0.0.9 release, so I'm going to use that for now.

I also noted that the Release page includes both 0.0.8 and 0.0.9 packages, which could indicate a bug in the CI script? https://github.com/SMI/IsIdentifiable/releases/tag/v0.0.9

**Comment by rkm** [comment]
Works with Terminal.Gui v1.8.2, but broken after this commit
