### ISSUE TITLE
`System.MissingMethodException: Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.LoadPixelData(Byte[], Int32, Int32)'

### ISSUE THREAD

**Issue by rkm** [SMI/IsIdentifiable#476]
```console
2024-04-22 14:07:33.2779|DEBUG|IsIdentifiable.Runners.DicomFileRunner|Opening File: ...||
2024-04-22 14:07:33.8434| INFO|IsIdentifiable.Runners.DicomFileRunner|Processing '...'||
2024-04-22 14:07:33.8715| INFO|IsIdentifiable.Runners.DicomFileRunner|Frame 0 in '...'||
2024-04-22 14:07:33.9430| INFO|IsIdentifiable.Runners.DicomFileRunner|Could not run Tesseract on '...'|System.MissingMethodException: Method not found: 'SixLabors.ImageSharp.Image`1<!!0> SixLabors.ImageSharp.Image.LoadPixelData(Byte[], Int32, Int32)'.
   at FellowOakDicom.Imaging.ImageSharpImage.Render(Int32 components, Boolean flipX, Boolean flipY, Int32 rotation)
   at FellowOakDicom.Imaging.Render.ImageGraphic.RenderImage(ILUT lut)
   at FellowOakDicom.Imaging.DicomImage.RenderImage(Int32 frame)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds, String modality, String[] imageTypeArr) in /home/runner/work/IsIdentif
iable/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 326|
```

**Comment by rkm** [comment]
@jas88 have you seen this before? Any ideas?
