### ISSUE TITLE
Could not run Tesseract ... Cannot access a disposed object Image`1

### ISSUE THREAD

**Issue by rkm** [SMI/IsIdentifiable#594]
IsIdentifiable service produced this error during the extraction pipeline, and sent the message to the dead-letter queue:

```console
Exception while classifying ExtractedFileStatusMessage:
System.ApplicationException: Could not run Tesseract on 'foo.dcm'
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Image`1'.
   at SixLabors.ImageSharp.Image.ThrowObjectDisposedException(Type type)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds, String modality, String[] imageTypeArr) in /home/runner/work/IsIdentifiable/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 334
   --- End of inner exception stack trace ---
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds, String modality, String[] imageTypeArr) in /home/runner/work/IsIdentifiable/IsIdentifiable/IsIdentifiable/Runners/Dicom
FileRunner.cs:line 429
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomFile(IFileInfo fi) in /home/runner/work/IsIdentifiable/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 208
   at SmiServices.Microservices.IsIdentifiable.IsIdentifiableQueueConsumer.ProcessMessageImpl(IMessageHeader header, ExtractedFileStatusMessage statusMessage, UInt64 tag) in /home/runner/work/SmiServices/SmiServices/src/SmiServices/Microse
rvices/IsIdentifiable/IsIdentifiableQueueConsumer.cs:line 64. File could not be scanned.
```

**Comment by rkm** [comment]
A second similar error was also produced by a different service instance on the same file:

```console
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryGroup'.
   at SixLabors.ImageSharp.Memory.MemoryGroup`1.Owned.ThrowObjectDisposedException()
   at SixLabors.ImageSharp.Memory.MemoryGroup`1.Owned.get_Item(Int32 index)
   at SixLabors.ImageSharp.Formats.Bmp.BmpEncoderCore.Write24BitPixelData[TPixel](Configuration configuration, Stream stream, Buffer2D`1 pixels)
   at SixLabors.ImageSharp.Formats.Bmp.BmpEncoderCore.WriteImage[TPixel](Configuration configuration, Stream stream, Image`1 image)
   at SixLabors.ImageSharp.Formats.Bmp.BmpEncoderCore.Encode[TPixel](Image`1 image, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageEncoder.Encode[TPixel](Image`1 image, Stream stream)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds, String modality, String[] imageTypeArr) in /home/runner/work/IsIdentifiable/IsIdentifiable/IsIdentifiable/Runners/Dicom
FileRunner.cs:line 334
   --- End of inner exception stack trace ---
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds, String modality, String[] imageTypeArr) in /home/runner/work/IsIdentifiable/IsIdentifiable/IsIdentifiable/Runners/Dicom
FileRunner.cs:line 429
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomFile(IFileInfo fi) in /home/runner/work/IsIdentifiable/IsIdentifiable/IsIdentifiable/Runners/DicomFileRunner.cs:line 208
   at SmiServices.Microservices.IsIdentifiable.IsIdentifiableQueueConsumer.ProcessMessageImpl(IMessageHeader header, ExtractedFileStatusMessage statusMessage, UInt64 tag) in /home/runner/work/SmiServices/SmiServices/src/SmiServices/Microse
rvices/IsIdentifiable/IsIdentifiableQueueConsumer.cs:line 64. File could not be scanned.
```

**Comment by jas88** [comment]
Interesting - I saw this crop up once in CI, but it didn't recur - I'd made a note at the time to go back and investigate in case it did come up a second time.
